openapi: '3.0.3'
info:
  title: Test OAuth2
  version: '1.0'
paths:
  /test1:
    get:
      parameters:
        - name: a
          in: query
          schema:
            type: string
      security:
        - authByOAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test1'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: string
        423:
          description: No response
components:
  securitySchemes:
    authByOAuth:
      type: oauth2
      flows:
        password:
          tokenUrl: https://example.org/auth/token
          refreshUrl: https://example.org/auth/token
        clientCredentials:
          tokenUrl: https://example.org/auth/token
        authorizationCode:
          authorizationUrl: https://example.org/auth/authorize
          tokenUrl: https://example.org/auth/token
  schemas:
    Test1:
      type: object
      properties:
        name:
          type: string
        size:
          type: integer
